### PR TITLE
Workaround for getting numpy.linalg.pinv argument default with numpy 1.17

### PR DESCRIPTION
**Pull request by paulromano**
This PR is one possible workaround for #89. I've confirmed locally that it does work in conjunction with numpy 1.17 installed from PyPI.

### CODE REVIEW

**Comment by toddrjen** [comment]
I am getting the following error with this patch:

```
======================================================================
ERROR: Interaction with NumPy, including matrix inversion,
----------------------------------------------------------------------
AttributeError: 'AffineScalarFunc' object has no attribute 'exp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/abuild/rpmbuild/BUILD/uncertainties-3.1.1/build/lib/uncertainties/unumpy/test_unumpy.py", line 64, in test_numpy
    numpy.exp(arr + ufloat(0, 0))
TypeError: loop of ufunc does not support argument 0 of type AffineScalarFunc which has no callable exp method

----------------------------------------------------------------------
```

**Comment by toddrme2178** [comment]
I am getting the following error under numpy 1.17 with this patch:

```
======================================================================
ERROR: Interaction with NumPy, including matrix inversion,
----------------------------------------------------------------------
AttributeError: 'AffineScalarFunc' object has no attribute 'exp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/abuild/rpmbuild/BUILD/uncertainties-3.1.1/build/lib/uncertainties/unumpy/test_unumpy.py", line 64, in test_numpy
    numpy.exp(arr + ufloat(0, 0))
TypeError: loop of ufunc does not support argument 0 of type AffineScalarFunc which has no callable exp method

----------------------------------------------------------------------
```

**Comment by paulromano** [comment]
Thanks for pointing that out @toddrme2178. It turns out that test failure with numpy 1.17 has nothing to do with the pinv issue. I'll fix the test to account for the new behavior in numpy 1.17 (see numpy/numpy#12700).
